function invValue = bilinear_interp(projectedValue, source)

        % floor and ceil of x and y
        xhigh = ceil(projectedValue(1));
        xlow = floor(projectedValue(1));
        
        yhigh = ceil(projectedValue(2));
        ylow = floor(projectedValue(2));
        
        invValue =  (1/(xhigh - xlow)*(yhigh - ylow))*...
                    (source(yhigh, xlow,:)*(xhigh - projectedValue(1))*...
                    (ylow - projectedValue(2)) + ...
                    source(yhigh, xhigh,:)*(projectedValue(1) - xlow)*...
                    (ylow - projectedValue(2)) + ...
                    source(ylow, xlow,:)*(xhigh - projectedValue(1))*...
                    (projectedValue(2) - yhigh) + ...
                    source(ylow, xhigh,:)*(projectedValue(1) -xlow)*...
                    (projectedValue(2)-yhigh));
                
                              
        
        
        

end